# Árboles de Regresión

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../datasets/boston/Boston.csv")
data.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [3]:
data.shape

(506, 14)

In [5]:
colnames = data.columns.values.tolist()
predictors = colnames[:13]
target = colnames[13]
X = data[predictors]
Y = data[target]

In [7]:
from sklearn.tree import DecisionTreeRegressor

In [25]:
regtree = DecisionTreeRegressor(min_samples_split=30, min_samples_leaf=10, max_depth=5, random_state=0)

In [26]:
regtree.fit(X,Y)

DecisionTreeRegressor(criterion='mse', max_depth=5, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=10,
           min_samples_split=30, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [27]:
preds = regtree.predict(data[predictors])

In [28]:
data["preds"] = preds

In [29]:
data[["preds", "medv"]]

         preds  medv
0    23.787500  24.0
1    23.787500  21.6
2    35.247826  34.7
3    35.247826  33.4
4    35.247826  36.2
5    23.787500  28.7
6    21.863636  22.9
7    20.020833  27.1
8    20.020833  16.5
9    20.020833  18.9
10   20.020833  15.0
11   21.863636  18.9
12   20.020833  21.7
13   23.787500  20.4
14   20.318750  18.2
15   23.787500  19.9
16   23.787500  23.1
17   17.233962  17.5
18   20.318750  20.2
19   20.318750  18.2
20   14.041667  13.6
21   20.318750  19.6
22   17.233962  15.2
23   14.041667  14.5
24   17.233962  15.6
25   17.233962  13.9
26   17.233962  16.6
27   17.233962  14.8
28   20.318750  18.4
29   20.318750  21.0
..         ...   ...
476  17.233962  16.7
477   9.913636  12.0
478  13.922222  14.6
479  20.318750  21.4
480  20.318750  23.0
481  23.787500  23.7
482  28.978261  25.0
483  20.318750  21.8
484  20.318750  20.6
485  20.318750  21.2
486  17.233962  19.1
487  20.318750  20.6
488  17.233962  15.2
489  14.041667   7.0
490  14.041667   8.1
491  17.233962  13.6
492  20.318750  20.1
493  20.318750  21.8
494  20.318750  24.5
495  17.233962  23.1
496  14.041667  19.7
497  20.318750  18.3
498  20.318750  21.2
499  17.233962  17.5
500  20.318750  16.8
501  23.787500  22.4
502  23.787500  20.6
503  28.978261  23.9
504  31.170000  22.0
505  23.787500  11.9

[506 rows x 2 columns]

In [1]:
from sklearn.tree import export_graphviz
with open("resources/boston_rtree.dot", "w") as dotfile:
    export_graphviz(regtree, out_file=dotfile, feature_names=predictors)
    dotfile.close()
    
import os
from graphviz import Source
file = open("resources/boston_rtree.dot", "r")
text = file.read()
#Source(text)

In [15]:
from sklearn.cross_validation import KFold
from sklearn.cross_validation import cross_val_score
import numpy as np

In [31]:
cv = KFold(n=X.shape[0], n_folds = 10, shuffle=True, random_state=1)
scores = cross_val_score(regtree, X, Y, scoring="mean_squared_error", cv = cv, n_jobs=1)
print(scores)
score = np.mean(scores)
print(score)

[-14.21501779 -16.62018743 -18.48312343 -46.22608214 -10.25202434
 -18.39546877 -15.08005674 -32.23929702 -23.04375075 -10.93761052]
-20.54926189262014

In [32]:
list(zip(predictors,regtree.feature_importances_))

[('crim', 0.032184533425691254),
 ('zn', 0.0),
 ('indus', 0.0),
 ('chas', 0.0),
 ('nox', 0.016195328299152056),
 ('rm', 0.6341876193016562),
 ('age', 0.014165271650613091),
 ('dis', 0.0),
 ('rad', 0.0),
 ('tax', 0.0),
 ('ptratio', 0.009620458196377114),
 ('black', 0.0),
 ('lstat', 0.2936467891265104)]

## Random Forests

In [33]:
from sklearn.ensemble import RandomForestRegressor

In [44]:
forest = RandomForestRegressor(n_jobs=2, oob_score=True, n_estimators=10000)
forest.fit(X,Y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10000, n_jobs=2,
           oob_score=True, random_state=None, verbose=0, warm_start=False)

In [45]:
data["rforest_pred"]= forest.oob_prediction_
data[["rforest_pred", "medv"]]

     rforest_pred  medv
0       28.481279  24.0
1       22.624058  21.6
2       34.585730  34.7
3       34.790003  33.4
4       34.323048  36.2
5       23.997725  28.7
6       20.229325  22.9
7       17.294122  27.1
8       17.910405  16.5
9       19.775659  18.9
10      20.693292  15.0
11      20.813106  18.9
12      21.245221  21.7
13      19.944679  20.4
14      19.966388  18.2
15      20.347713  19.9
16      21.397943  23.1
17      18.328238  17.5
18      18.738948  20.2
19      19.772087  18.2
20      14.508871  13.6
21      18.584422  19.6
22      16.068443  15.2
23      15.013955  14.5
24      16.630460  15.6
25      15.760181  13.9
26      17.402940  16.6
27      15.118416  14.8
28      20.057530  18.4
29      23.006519  21.0
..            ...   ...
476     16.016040  16.7
477     13.579000  12.0
478     14.573479  14.6
479     20.076588  21.4
480     21.017078  23.0
481     28.701422  23.7
482     32.116689  25.0
483     20.267125  21.8
484     20.983144  20.6
485     22.013684  21.2
486     19.040222  19.1
487     21.368733  20.6
488     14.401306  15.2
489     13.073253   7.0
490     10.850246   8.1
491     16.120535  13.6
492     20.220841  20.1
493     19.672850  21.8
494     20.752433  24.5
495     19.425565  23.1
496     18.670488  19.7
497     20.333564  18.3
498     21.284089  21.2
499     19.855477  17.5
500     20.299728  16.8
501     24.289566  22.4
502     18.987793  20.6
503     27.636796  23.9
504     26.192514  22.0
505     20.897088  11.9

[506 rows x 2 columns]

In [46]:
data["rforest_error2"] = (data["rforest_pred"]-data["medv"])**2
sum(data["rforest_error2"])/len(data)

10.234649905954406

In [47]:
forest.oob_score_

0.8787644667661886